# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygesture/ui/templates/new_session_template.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewSessionDialog(object):
    def setupUi(self, NewSessionDialog):
        NewSessionDialog.setObjectName("NewSessionDialog")
        NewSessionDialog.setWindowModality(QtCore.Qt.NonModal)
        NewSessionDialog.resize(288, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewSessionDialog.sizePolicy().hasHeightForWidth())
        NewSessionDialog.setSizePolicy(sizePolicy)
        NewSessionDialog.setSizeGripEnabled(False)
        NewSessionDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(NewSessionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.participantLabel = QtWidgets.QLabel(NewSessionDialog)
        self.participantLabel.setObjectName("participantLabel")
        self.gridLayout.addWidget(self.participantLabel, 0, 0, 1, 1)
        self.participantLineEdit = QtWidgets.QLineEdit(NewSessionDialog)
        self.participantLineEdit.setObjectName("participantLineEdit")
        self.gridLayout.addWidget(self.participantLineEdit, 0, 1, 1, 1)
        self.sessionLabel = QtWidgets.QLabel(NewSessionDialog)
        self.sessionLabel.setObjectName("sessionLabel")
        self.gridLayout.addWidget(self.sessionLabel, 1, 0, 1, 1)
        self.sessionLineEdit = QtWidgets.QLineEdit(NewSessionDialog)
        self.sessionLineEdit.setObjectName("sessionLineEdit")
        self.gridLayout.addWidget(self.sessionLineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(NewSessionDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.taskComboBox = QtWidgets.QComboBox(NewSessionDialog)
        self.taskComboBox.setObjectName("taskComboBox")
        self.gridLayout.addWidget(self.taskComboBox, 2, 1, 1, 1)
        self.configurationLabel = QtWidgets.QLabel(NewSessionDialog)
        self.configurationLabel.setObjectName("configurationLabel")
        self.gridLayout.addWidget(self.configurationLabel, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.armRadioButton = QtWidgets.QRadioButton(NewSessionDialog)
        self.armRadioButton.setChecked(True)
        self.armRadioButton.setObjectName("armRadioButton")
        self.configurationGroup = QtWidgets.QButtonGroup(NewSessionDialog)
        self.configurationGroup.setObjectName("configurationGroup")
        self.configurationGroup.addButton(self.armRadioButton)
        self.horizontalLayout.addWidget(self.armRadioButton)
        self.legRadioButton = QtWidgets.QRadioButton(NewSessionDialog)
        self.legRadioButton.setObjectName("legRadioButton")
        self.configurationGroup.addButton(self.legRadioButton)
        self.horizontalLayout.addWidget(self.legRadioButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(NewSessionDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(NewSessionDialog)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.handGroup = QtWidgets.QButtonGroup(NewSessionDialog)
        self.handGroup.setObjectName("handGroup")
        self.handGroup.addButton(self.radioButton)
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(NewSessionDialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.handGroup.addButton(self.radioButton_2)
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewSessionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(NewSessionDialog)
        self.buttonBox.accepted.connect(NewSessionDialog.accept)
        self.buttonBox.rejected.connect(NewSessionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewSessionDialog)
        NewSessionDialog.setTabOrder(self.participantLineEdit, self.sessionLineEdit)
        NewSessionDialog.setTabOrder(self.sessionLineEdit, self.taskComboBox)
        NewSessionDialog.setTabOrder(self.taskComboBox, self.armRadioButton)
        NewSessionDialog.setTabOrder(self.armRadioButton, self.legRadioButton)
        NewSessionDialog.setTabOrder(self.legRadioButton, self.radioButton)
        NewSessionDialog.setTabOrder(self.radioButton, self.radioButton_2)

    def retranslateUi(self, NewSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        NewSessionDialog.setWindowTitle(_translate("NewSessionDialog", "New Session"))
        self.participantLabel.setText(_translate("NewSessionDialog", "Participant ID:"))
        self.sessionLabel.setText(_translate("NewSessionDialog", "Session ID:"))
        self.label_3.setText(_translate("NewSessionDialog", "Task:"))
        self.configurationLabel.setText(_translate("NewSessionDialog", "Configuration:"))
        self.armRadioButton.setText(_translate("NewSessionDialog", "arm"))
        self.legRadioButton.setText(_translate("NewSessionDialog", "leg"))
        self.label_2.setText(_translate("NewSessionDialog", "Hand:"))
        self.radioButton.setText(_translate("NewSessionDialog", "right"))
        self.radioButton_2.setText(_translate("NewSessionDialog", "left"))

