# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygesture/ui/templates/train_widget_template.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrainWidget(object):
    def setupUi(self, TrainWidget):
        TrainWidget.setObjectName("TrainWidget")
        TrainWidget.resize(698, 325)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TrainWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(TrainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.promptWidget = PromptWidget(self.frame_2)
        self.promptWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.promptWidget.setProperty("value", 0)
        self.promptWidget.setTextVisible(False)
        self.promptWidget.setOrientation(QtCore.Qt.Horizontal)
        self.promptWidget.setObjectName("promptWidget")
        self.gridLayout.addWidget(self.promptWidget, 1, 0, 1, 1)
        self.gestureView = GestureView(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gestureView.sizePolicy().hasHeightForWidth())
        self.gestureView.setSizePolicy(sizePolicy)
        self.gestureView.setObjectName("gestureView")
        self.gridLayout.addWidget(self.gestureView, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(TrainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(17, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.statusBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBox.sizePolicy().hasHeightForWidth())
        self.statusBox.setSizePolicy(sizePolicy)
        self.statusBox.setObjectName("statusBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.statusBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sessionProgressBar = QtWidgets.QProgressBar(self.statusBox)
        self.sessionProgressBar.setProperty("value", 24)
        self.sessionProgressBar.setObjectName("sessionProgressBar")
        self.gridLayout_5.addWidget(self.sessionProgressBar, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.statusBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.startButton.setIcon(icon)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.statusBox)
        self.pauseButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.pauseButton.setIcon(icon)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.statusBox, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(TrainWidget)
        QtCore.QMetaObject.connectSlotsByName(TrainWidget)

    def retranslateUi(self, TrainWidget):
        _translate = QtCore.QCoreApplication.translate
        TrainWidget.setWindowTitle(_translate("TrainWidget", "Form"))
        self.statusBox.setTitle(_translate("TrainWidget", "Controls"))
        self.sessionProgressBar.setFormat(_translate("TrainWidget", "Trial: %v / %m"))
        self.startButton.setText(_translate("TrainWidget", "Start"))
        self.pauseButton.setText(_translate("TrainWidget", "Pause"))

from pygesture.ui.widgets import GestureView, PromptWidget
