# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygesture/ui/test_template.ui'
#
# Created: Wed Apr  1 17:10:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(843, 545)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gestureDisplayLabel = GestureView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gestureDisplayLabel.sizePolicy().hasHeightForWidth())
        self.gestureDisplayLabel.setSizePolicy(sizePolicy)
        self.gestureDisplayLabel.setText(_fromUtf8(""))
        self.gestureDisplayLabel.setScaledContents(False)
        self.gestureDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gestureDisplayLabel.setObjectName(_fromUtf8("gestureDisplayLabel"))
        self.gridLayout.addWidget(self.gestureDisplayLabel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mainDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainDock.sizePolicy().hasHeightForWidth())
        self.mainDock.setSizePolicy(sizePolicy)
        self.mainDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.mainDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.mainDock.setObjectName(_fromUtf8("mainDock"))
        self.mainDockContents = QtGui.QWidget()
        self.mainDockContents.setObjectName(_fromUtf8("mainDockContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mainDockContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mainDockScrollArea = QtGui.QScrollArea(self.mainDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainDockScrollArea.sizePolicy().hasHeightForWidth())
        self.mainDockScrollArea.setSizePolicy(sizePolicy)
        self.mainDockScrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainDockScrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.mainDockScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mainDockScrollArea.setWidgetResizable(True)
        self.mainDockScrollArea.setObjectName(_fromUtf8("mainDockScrollArea"))
        self.mainDockScrollContents = QtGui.QWidget()
        self.mainDockScrollContents.setGeometry(QtCore.QRect(0, 0, 300, 436))
        self.mainDockScrollContents.setObjectName(_fromUtf8("mainDockScrollContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mainDockScrollContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.startButton = QtGui.QPushButton(self.mainDockScrollContents)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.gridLayout_3.addWidget(self.startButton, 1, 0, 1, 1)
        self.sessionInfoBox = QtGui.QGroupBox(self.mainDockScrollContents)
        self.sessionInfoBox.setObjectName(_fromUtf8("sessionInfoBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.sessionInfoBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.trainingLabel = QtGui.QLabel(self.sessionInfoBox)
        self.trainingLabel.setObjectName(_fromUtf8("trainingLabel"))
        self.verticalLayout.addWidget(self.trainingLabel)
        self.trainingList = QtGui.QListWidget(self.sessionInfoBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainingList.sizePolicy().hasHeightForWidth())
        self.trainingList.setSizePolicy(sizePolicy)
        self.trainingList.setProperty("showDropIndicator", False)
        self.trainingList.setAlternatingRowColors(False)
        self.trainingList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.trainingList.setResizeMode(QtGui.QListView.Fixed)
        self.trainingList.setObjectName(_fromUtf8("trainingList"))
        self.verticalLayout.addWidget(self.trainingList)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pidLabel = QtGui.QLabel(self.sessionInfoBox)
        self.pidLabel.setObjectName(_fromUtf8("pidLabel"))
        self.horizontalLayout.addWidget(self.pidLabel)
        self.pidComboBox = QtGui.QComboBox(self.sessionInfoBox)
        self.pidComboBox.setObjectName(_fromUtf8("pidComboBox"))
        self.horizontalLayout.addWidget(self.pidComboBox)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.classifierLabel = QtGui.QLabel(self.sessionInfoBox)
        self.classifierLabel.setObjectName(_fromUtf8("classifierLabel"))
        self.horizontalLayout_2.addWidget(self.classifierLabel)
        self.classifierComboBox = QtGui.QComboBox(self.sessionInfoBox)
        self.classifierComboBox.setObjectName(_fromUtf8("classifierComboBox"))
        self.classifierComboBox.addItem(_fromUtf8(""))
        self.classifierComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.classifierComboBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.sessionInfoBox, 0, 0, 1, 1)
        self.mainDockScrollArea.setWidget(self.mainDockScrollContents)
        self.gridLayout_2.addWidget(self.mainDockScrollArea, 0, 0, 1, 1)
        self.mainDock.setWidget(self.mainDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.mainDock)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_Quit.setIcon(icon)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("window-new"))
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionProbe = QtGui.QAction(MainWindow)
        self.actionProbe.setObjectName(_fromUtf8("actionProbe"))
        self.actionCheck_Signals = QtGui.QAction(MainWindow)
        self.actionCheck_Signals.setObjectName(_fromUtf8("actionCheck_Signals"))
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addAction(self.actionSettings)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.toolBar.addAction(self.actionCalibrate)
        self.toolBar.addAction(self.actionProbe)
        self.toolBar.addAction(self.actionCheck_Signals)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pygesture-test", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.mainDock.setWindowTitle(_translate("MainWindow", "Controls", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.sessionInfoBox.setTitle(_translate("MainWindow", "Session Info", None))
        self.trainingLabel.setText(_translate("MainWindow", "Training Data:", None))
        self.pidLabel.setText(_translate("MainWindow", "Participant ID:", None))
        self.classifierLabel.setText(_translate("MainWindow", "Classifier:", None))
        self.classifierComboBox.setItemText(0, _translate("MainWindow", "LDA", None))
        self.classifierComboBox.setItemText(1, _translate("MainWindow", "SVM", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionNew.setText(_translate("MainWindow", "&New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.actionCalibrate.setToolTip(_translate("MainWindow", "Calibrate input signals", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))
        self.actionProbe.setText(_translate("MainWindow", "Probe...", None))
        self.actionCheck_Signals.setText(_translate("MainWindow", "Check Signals", None))

from pygesture.ui.widgets import GestureView
