# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygesture/ui/test_widget_template.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestWidget(object):
    def setupUi(self, TestWidget):
        TestWidget.setObjectName("TestWidget")
        TestWidget.resize(678, 454)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(TestWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(TestWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gestureDisplayLabel = GestureView(self.frame_2)
        self.gestureDisplayLabel.setObjectName("gestureDisplayLabel")
        self.gridLayout_2.addWidget(self.gestureDisplayLabel, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(TestWidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.startButton = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.startButton.setIcon(icon)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 3, 0, 1, 1)
        self.sessionInfoBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionInfoBox.sizePolicy().hasHeightForWidth())
        self.sessionInfoBox.setSizePolicy(sizePolicy)
        self.sessionInfoBox.setObjectName("sessionInfoBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sessionInfoBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classifierLabel = QtWidgets.QLabel(self.sessionInfoBox)
        self.classifierLabel.setObjectName("classifierLabel")
        self.horizontalLayout.addWidget(self.classifierLabel)
        self.classifierComboBox = QtWidgets.QComboBox(self.sessionInfoBox)
        self.classifierComboBox.setObjectName("classifierComboBox")
        self.classifierComboBox.addItem("")
        self.classifierComboBox.addItem("")
        self.horizontalLayout.addWidget(self.classifierComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.trainingLabel = QtWidgets.QLabel(self.sessionInfoBox)
        self.trainingLabel.setObjectName("trainingLabel")
        self.verticalLayout.addWidget(self.trainingLabel)
        self.trainingList = QtWidgets.QListWidget(self.sessionInfoBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainingList.sizePolicy().hasHeightForWidth())
        self.trainingList.setSizePolicy(sizePolicy)
        self.trainingList.setProperty("showDropIndicator", False)
        self.trainingList.setAlternatingRowColors(False)
        self.trainingList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.trainingList.setResizeMode(QtWidgets.QListView.Fixed)
        self.trainingList.setObjectName("trainingList")
        self.verticalLayout.addWidget(self.trainingList)
        self.trainButton = QtWidgets.QPushButton(self.sessionInfoBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainButton.sizePolicy().hasHeightForWidth())
        self.trainButton.setSizePolicy(sizePolicy)
        self.trainButton.setDefault(False)
        self.trainButton.setFlat(False)
        self.trainButton.setObjectName("trainButton")
        self.verticalLayout.addWidget(self.trainButton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sessionInfoBox, 0, 0, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon.fromTheme("insert-link")
        self.connectButton.setIcon(icon)
        self.connectButton.setCheckable(True)
        self.connectButton.setChecked(False)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 2, 0, 1, 1)
        self.sessionBox = QtWidgets.QGroupBox(self.frame)
        self.sessionBox.setObjectName("sessionBox")
        self.formLayout = QtWidgets.QFormLayout(self.sessionBox)
        self.formLayout.setObjectName("formLayout")
        self.sessionTypeLabel = QtWidgets.QLabel(self.sessionBox)
        self.sessionTypeLabel.setObjectName("sessionTypeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sessionTypeLabel)
        self.sessionTypeComboBox = QtWidgets.QComboBox(self.sessionBox)
        self.sessionTypeComboBox.setObjectName("sessionTypeComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sessionTypeComboBox)
        self.gridLayout.addWidget(self.sessionBox, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame)

        self.retranslateUi(TestWidget)
        QtCore.QMetaObject.connectSlotsByName(TestWidget)

    def retranslateUi(self, TestWidget):
        _translate = QtCore.QCoreApplication.translate
        TestWidget.setWindowTitle(_translate("TestWidget", "Form"))
        self.startButton.setText(_translate("TestWidget", "Start"))
        self.sessionInfoBox.setTitle(_translate("TestWidget", "Classification"))
        self.classifierLabel.setText(_translate("TestWidget", "Classifier:"))
        self.classifierComboBox.setItemText(0, _translate("TestWidget", "LDA"))
        self.classifierComboBox.setItemText(1, _translate("TestWidget", "SVM"))
        self.trainingLabel.setText(_translate("TestWidget", "Training Data:"))
        self.trainButton.setText(_translate("TestWidget", "Train"))
        self.connectButton.setText(_translate("TestWidget", "Connect"))
        self.sessionBox.setTitle(_translate("TestWidget", "Session"))
        self.sessionTypeLabel.setText(_translate("TestWidget", "Type:"))

from pygesture.ui.widgets import GestureView
