# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygesture/ui/train_template.ui'
#
# Created: Wed Apr  1 17:10:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(827, 547)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gestureView = GestureView(self.centralwidget)
        self.gestureView.setText(_fromUtf8(""))
        self.gestureView.setObjectName(_fromUtf8("gestureView"))
        self.gridLayout.addWidget(self.gestureView, 0, 0, 1, 1)
        self.promptWidget = PromptWidget(self.centralwidget)
        self.promptWidget.setObjectName(_fromUtf8("promptWidget"))
        self.gridLayout.addWidget(self.promptWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.controlsDockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsDockWidget.sizePolicy().hasHeightForWidth())
        self.controlsDockWidget.setSizePolicy(sizePolicy)
        self.controlsDockWidget.setMinimumSize(QtCore.QSize(250, 107))
        self.controlsDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.controlsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.controlsDockWidget.setObjectName(_fromUtf8("controlsDockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 467))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.statusBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.statusBox.setObjectName(_fromUtf8("statusBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.statusBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sessionProgressBar = QtGui.QProgressBar(self.statusBox)
        self.sessionProgressBar.setProperty("value", 24)
        self.sessionProgressBar.setObjectName(_fromUtf8("sessionProgressBar"))
        self.gridLayout_5.addWidget(self.sessionProgressBar, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startButton = QtGui.QPushButton(self.statusBox)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseButton = QtGui.QPushButton(self.statusBox)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.horizontalLayout.addWidget(self.pauseButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.statusBox, 2, 0, 1, 1)
        self.sessionInfoBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionInfoBox.sizePolicy().hasHeightForWidth())
        self.sessionInfoBox.setSizePolicy(sizePolicy)
        self.sessionInfoBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sessionInfoBox.setFlat(False)
        self.sessionInfoBox.setCheckable(False)
        self.sessionInfoBox.setObjectName(_fromUtf8("sessionInfoBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.sessionInfoBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.participantLabel = QtGui.QLabel(self.sessionInfoBox)
        self.participantLabel.setObjectName(_fromUtf8("participantLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.participantLabel)
        self.participantLineEdit = QtGui.QLineEdit(self.sessionInfoBox)
        self.participantLineEdit.setObjectName(_fromUtf8("participantLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.participantLineEdit)
        self.sessionLabel = QtGui.QLabel(self.sessionInfoBox)
        self.sessionLabel.setObjectName(_fromUtf8("sessionLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.sessionLabel)
        self.sessionLineEdit = QtGui.QLineEdit(self.sessionInfoBox)
        self.sessionLineEdit.setObjectName(_fromUtf8("sessionLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sessionLineEdit)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.sessionInfoBox, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.controlsDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlsDockWidget)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionProbe = QtGui.QAction(MainWindow)
        self.actionProbe.setObjectName(_fromUtf8("actionProbe"))
        self.actionCheckSignals = QtGui.QAction(MainWindow)
        self.actionCheckSignals.setObjectName(_fromUtf8("actionCheckSignals"))
        self.menu_File.addAction(self.actionExit)
        self.menu_View.addAction(self.actionProbe)
        self.menu_View.addAction(self.actionCheckSignals)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pygesture-train", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.controlsDockWidget.setWindowTitle(_translate("MainWindow", "Controls", None))
        self.statusBox.setTitle(_translate("MainWindow", "Status", None))
        self.sessionProgressBar.setFormat(_translate("MainWindow", "Trial: %v / %m", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.pauseButton.setText(_translate("MainWindow", "Pause", None))
        self.sessionInfoBox.setTitle(_translate("MainWindow", "Session Info", None))
        self.participantLabel.setText(_translate("MainWindow", "Participant:", None))
        self.sessionLabel.setText(_translate("MainWindow", "Session:", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionProbe.setText(_translate("MainWindow", "Probe", None))
        self.actionCheckSignals.setText(_translate("MainWindow", "Check Signals", None))

from pygesture.ui.widgets import PromptWidget, GestureView
